site_name: Student Manager Documentation
site_url: https://www.studentmanager.co.za
repo_url: https://github.com/AgileSystemsTechnology/StudentManager.Docs
site_favicon: favicon.ico

pages:
- Home: index.md

- Basic Setup: smbasicsetup/basicsetup.md
- Add a Qualification: Qualifications/addaqualification.md
- Add a Module: Modules/addamodule.md
- Add a Group: Groups/settingupmodulegroups.md
- Add a Curriculum: Qualifications/setupcurriculums.md
- Add an Intake: Qualifications/addapplicationintake.md

- Login:
    - Password Reset: Login/loginpasswordreset.md
   
- People:
    - Adding People - Staff: People/adding-people.md
    - Staff/Employee System Access: People/employeesystemaccess.md
    - Finding People: People/finding-people.md
    - Bulk Activation Link: People/bulkactivationlinks.md
    - Set up for Details Update Requests: People/userprofiledetailsupdatesetup.md
    - Sending Profile Details Update Request: People/userprofileupdatescreate.md
    - Viewing Student Coursewowrk: People/viewingstudentcoursework.md

- People Settings:
    - Disable requiring ID for creating a user: PeopleSettings/disableidrequired.md

- Modules:
    - Add a Module: Modules/addamodule.md
    - Moving Modules: Modules/movingmodules.md
    - Searching for a Module: Modules/findingmodules.md
    - Make a Module inactive i.e. deactivate: Modules/deactivateamodule.md
    - Viewing deativated modules: Modules/showhideinactivemodules.md
    - Setting inactive modules to active: Modules/makeinactivemoduleactive.md
    - Setting up Module Groups: Modules/settingupmodulegroups.md
    - Setting Up Assessments: Modules/settingupassessments.md
    - Assessment Attempts: Modules/assessmentattempts.md
    - Copy Assessments in Bulk: Modules/copyassessmentsinbulk.md
    - Online Tests: Modules/onlinetests.md
    - Online Assessment: Modules/onlineassessments.md
    - Grade Assessments: Modules/grading.md
    - Adding E-Learning Material: Modules/addinglearningmaterial.md 
    - Merging Duplicate Modules: Modules/mergingduplicatemodules.md

- Groups:
    - Setting up Module Groups: Groups/settingupmodulegroups.md

- Qualifications:
    - Add a Qualification: Qualifications/addaqualification.md
    - Add a Module: Modules/addamodule.md
    - Add a Group: Groups/settingupmodulegroups.md
	- Add a Curriculum:  Qualifications/setupcurriculums.md
	- Add an Intake: Qualifications/addapplicationintake.md
	- Searching for a Qualification: Qualifications/searchingandviewingaqualification.md
	- Adding a New Application Wizard: Qualifications/addingnewapplicationwizard.md
	- Adding a Application Wizard Step: Qualifications/addingsectionstoapplicationwizardsteps.md
	- Adding sections to an Application Wizard Step: Qualifications/addingsectionstoapplicationwizardsteps.md

- Registrations:
    - Registering Modules From Student Profile: Registration/registeringlearnermodulesfromstudentprofile.md
    - Registering Module from Registrations: Registration/registeringlearnermodulesfromreg.md
    - Registering Modules after Applications: Registration/registerintlearnermodulesafterapplication.md
    - Registration Group dates edit: Registration/registrationgroupdatesedit.md
    - Registering Modules for students in bulk: Registration/registeringlearnermodulesinbulk.md

- Reports:
    - Print a Lecture Time Table: Reports/printalecturetimetable.md
    - Print a Student Card: Reports/printingastudentcard.md
    - Printing Academic Transcripts: Reports/printingacademictranscripts.md

- Calendar:
    - Create Events: Calendar/createevents.md 

- Leads:
    - Navigation: Leads/leadsnavigation.md

- Applicants:
    - Adding a New Applicant: Applications/addinganewapplicant.md
    - Adding a New Applicant from Existing Users: Applications/addinganewapplicantfromexisting.md
    - Editing the Applications Close date: Applications/changingclosedate.md
        
- Communication:
    - Creating an Inbox: Communication/settingsupaninbox.md
    - Sending an SMS: Communication/sendingansms.md

- Moodle:
    - Moodle Integration: Moodle/moodleintegration.md


- More:
    - Creating and Moving Logs: More/creatingormovinglogs.md
    - Grade and Symbol Settings: More/gradeandsymbolsettings.md

    
theme: readthedocs
